@info_by_service_id = lambda do |service_id|
  query "SELECT DISTINCT
  A .SERVICE_ID,
  A .USER_ID,
  A .ACCOUNT_ID,
  A .PRESERVE02,
  G .SERVICE_NAME,
  B .F_AREA_NAME,
  C .FIRST_NAME,
  --C .IDENTITY_CODE,
  D .F_PROD_NAME,
  D .F_IF_3G,
  E .NAME,
  A .APPLY_START_DATE,
  G .DEV_NAME,
  F .DEALER_NAME,
  A .STATUS_CHANGE_DATE,
  A .SERVICE_STOP_DATE
  FROM
  BB_SERVICE_RELATION_T A
  LEFT JOIN OM_AREA_T B ON A .BELONG_CODE = B.F_AREA_ID
  INNER JOIN BB_CUSTOMER_INFO_T C ON A .CUSTOMER_ID = C.CUSTOMER_ID
  INNER JOIN PM_PRODUCT_T D ON A .SERVICE_FAVOUR_ID = D .F_PROD_ID
  INNER JOIN BB_SERVING_STATUS_T E ON A .SERVING_STATUS = E .KIND
  LEFT JOIN BD_DEALER_T F ON A .DEVELOPER_DEALER = F.DEALER_ID
  LEFT JOIN UNI_DEALER_DEVELOPER_T@BILL2CRM G ON A .DEVELOPER = G .DEV_CODE
  INNER JOIN BS_SERVICE_KIND_T G ON A .SERVICE_KIND = G .SERVICE_KIND
  WHERE
  A .CITY_CODE = '847'
  AND A .IF_VALID = '1'
  AND A .SERVICE_ID IN ('#{service_id}')
  ORDER BY
  A .SERVICE_ID ASC"
end
